### examples/train_lora/llama3_lora_sft.yaml
model_name_or_path: /home/zhusy/modles/Qwen/Qwen2___5-7B-Instruct
# flash_attn: fa2

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: sft_single_train_correct
dataset_dir: data  
eval_dataset: sft_single_valid_correct
# 数据集目录
overwrite_cache: true
preprocessing_num_workers: 16

template: qwen
cutoff_len: 1024
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16
report_to: none
output_dir: saves/qwen/qwen2.5-7b-lora-single-correct
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

lora_rank: 8
lora_alpha: 32
lora_dropout: 0.1